paths:
  /call:
    get:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: CallController_findAll
    post:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: CallController_create
  /call/{id}:
    get:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: CallController_findOne
    delete:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: CallController_deleteCallData
    patch:
      x-fern-sdk-group-name:
        - calls
      x-fern-sdk-method-name: CallController_update
  /assistant:
    get:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: AssistantController_findAll
    post:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: AssistantController_create
  /assistant/{id}:
    get:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: AssistantController_findOne
    delete:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: AssistantController_remove
    patch:
      x-fern-sdk-group-name:
        - assistants
      x-fern-sdk-method-name: AssistantController_update
  /phone-number:
    get:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: PhoneNumberController_findAll
    post:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: PhoneNumberController_create
  /phone-number/{id}:
    get:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: PhoneNumberController_findOne
    delete:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: PhoneNumberController_remove
    patch:
      x-fern-sdk-group-name:
        - phoneNumbers
      x-fern-sdk-method-name: PhoneNumberController_update
  /squad:
    get:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: SquadController_findAll
    post:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: SquadController_create
  /squad/{id}:
    get:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: SquadController_findOne
    delete:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: SquadController_remove
    patch:
      x-fern-sdk-group-name:
        - squads
      x-fern-sdk-method-name: SquadController_update
  /block:
    get:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: BlockController_findAll
    post:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: BlockController_create
  /block/{id}:
    get:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: BlockController_findOne
    delete:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: BlockController_remove
    patch:
      x-fern-sdk-group-name:
        - blocks
      x-fern-sdk-method-name: BlockController_update
  /tool:
    get:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: ToolController_findAll
    post:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: ToolController_create
  /tool/{id}:
    get:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: ToolController_findOne
    delete:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: ToolController_remove
    patch:
      x-fern-sdk-group-name:
        - tools
      x-fern-sdk-method-name: ToolController_update
  /file:
    get:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: FileController_findAll
    post:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: FileController_create
  /file/{id}:
    get:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: FileController_findOne
    delete:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: FileController_remove
    patch:
      x-fern-sdk-group-name:
        - files
      x-fern-sdk-method-name: FileController_update
  /analytics:
    post:
      x-fern-sdk-group-name:
        - analytics
      x-fern-sdk-method-name: AnalyticsController_query
  /logs:
    get:
      x-fern-sdk-group-name:
        - logs
      x-fern-sdk-method-name: LoggingController_queryLogs
